---
language: java
sudo: false
install: true

jdk:
  - openjdk8
  - openjdk11
  - openjdk17
  - oraclejdk11
  - oraclejdk17

script:
  - "./runSonarQubeAnalysis.sh"

cache:
  directories:
    - "${HOME}/.m2/repository"
    - "${HOME}/.sonar/cache"

notifications:
  email: true

env:
  global:
    - secure: 
    - SONAR_HOST_URL=https://sonarqube.com
